name: 'Godot Export'
description: 'Generate a godot binary from the repository'
inputs:
  export-template:  # id of input
    description: 'Template name to use for exporting the project'
    required: true
  output-filename:
    description: 'Name of the generated executable'
    required: true
  godot-version:
    description: 'Version of godot required to build the project'
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - run: mkdir output
      shell: bash
    - run: docker run -v $(pwd):/mnt "gamedrivendesign/godot-export:${{ inputs.godot-version }}" /build/godot --export "${{ inputs.export-template }}" --path /mnt "/mnt/output/${{ inputs.output-filename }}"
      shell: bash
